import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/shared/NavBar";
import Footer from "@/components/shared/Footer";
import AuthProvider from "@/Authentication/AuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Car Doctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      

        <body  className="inter.className min-h-screen">

        <AuthProvider>

<NavBar/>


<div className="min-h-screen">  {children} </div>


<Footer/>



</AuthProvider>


        </body>
    
    
      
    </html>
  );
}
